/**
 * Types for multi-source "open" quiz generation.
 */

/**
 * Supported source types for open mode.
 */
export type SourceType = 'github' | 'url' | 'confluence' | 'notion' | 'file';

/**
 * Specification for a content source.
 * Format: TYPE:TARGET (e.g., "github:owner/repo", "url:https://docs.example.com")
 */
export interface SourceSpec {
  type: SourceType;
  target: string;
  /** Subtype for sources that have variations (e.g., 'repo', 'pr' for github) */
  subtype?: string;
}

/**
 * A concept extracted from a source.
 */
export interface ExtractedConcept {
  id: string;
  name: string;
  definition: string;
  /** Related concept IDs */
  relatedTo?: string[];
}

/**
 * A fact extracted from a source.
 */
export interface ExtractedFact {
  statement: string;
  quizWorthy: boolean;
  /** Source location or reference */
  reference?: string;
}

/**
 * A potential question outline.
 */
export interface QuestionOutline {
  topic: string;
  difficulty: number;
  outline: string;
  questionType?: 'multiple-choice' | 'multi-select' | 'free-text';
}

/**
 * Notes generated by a source explorer agent.
 */
export interface SourceNotes {
  source: SourceSpec;
  /** High-level summary of the source content */
  summary: string;
  /** Key concepts identified in the source */
  concepts: ExtractedConcept[];
  /** Important facts extracted */
  facts: ExtractedFact[];
  /** Potential quiz question ideas */
  potentialQuestions: QuestionOutline[];
  /** Timestamp when notes were generated */
  generatedAt: string;
  /** Any errors encountered during exploration */
  errors?: string[];
}

/**
 * Connections identified between sources.
 */
export interface SourceConnection {
  /** Source indices that share this connection */
  sourceIndices: number[];
  /** Theme or topic that connects the sources */
  theme: string;
  /** Description of how the sources relate */
  description: string;
  /** Related concept IDs from different sources */
  relatedConcepts: string[];
}

/**
 * Output from the connection finder agent.
 */
export interface ConnectionAnalysis {
  /** Cross-source themes and connections */
  connections: SourceConnection[];
  /** Suggested quiz focus areas based on connections */
  suggestedFocusAreas: string[];
  /** Concepts that appear across multiple sources */
  sharedConcepts: string[];
}

/**
 * Configuration for open mode quiz generation.
 */
export interface OpenModeConfig {
  /** Maximum number of concurrent explorer agents (default: 4) */
  maxAgents: number;
  /** Maximum turns per agent (default: 15) */
  maxIterations: number;
  /** Model to use for source exploration (default: 'claude-sonnet-4-6') */
  explorerModel: 'sonnet' | 'opus' | 'haiku';
  /** Model to use for quiz synthesis (default: 'claude-opus-4-6') */
  synthesizerModel: 'sonnet' | 'opus' | 'haiku';
}

/**
 * Default configuration for open mode.
 */
export const defaultOpenModeConfig: OpenModeConfig = {
  maxAgents: 4,
  maxIterations: 15,
  explorerModel: 'sonnet',
  synthesizerModel: 'opus',
};

/**
 * Session state for open mode generation.
 */
export interface OpenModeSession {
  /** Unique session identifier */
  id: string;
  /** Input sources */
  sources: SourceSpec[];
  /** User's prompt/focus */
  prompt: string;
  /** Configuration used */
  config: OpenModeConfig;
  /** Session directory path */
  sessionDir: string;
  /** Notes from each source explorer */
  notes: SourceNotes[];
  /** Connection analysis results */
  connections?: ConnectionAnalysis;
  /** Session status */
  status: 'exploring' | 'connecting' | 'synthesizing' | 'completed' | 'failed';
  /** Start time */
  startedAt: string;
  /** Completion time */
  completedAt?: string;
  /** Final quiz output path */
  outputPath?: string;
}

/**
 * Progress update for open mode generation.
 */
export interface OpenModeProgress {
  phase: 'exploring' | 'connecting' | 'synthesizing';
  /** Current phase progress (0-100) */
  progress: number;
  /** Human-readable status message */
  message: string;
  /** Number of sources completed (for exploring phase) */
  sourcesCompleted?: number;
  /** Total number of sources */
  totalSources?: number;
}

/**
 * Result of open mode generation.
 */
export interface OpenModeResult {
  success: boolean;
  /** Path to generated quiz JSON */
  quizPath?: string;
  /** Path to session directory with notes and artifacts */
  sessionDir: string;
  /** Error message if failed */
  error?: string;
  /** Generation statistics */
  stats: {
    totalSources: number;
    successfulSources: number;
    conceptsExtracted: number;
    connectionsFound: number;
    questionsGenerated: number;
    durationMs: number;
  };
}
